### ISSUE TITLE
Documentation for send_direct_message unclear

### ISSUE THREAD

**Issue by lancew** [semifor/Net-Twitter#40]
When sending a DM the following response is received (The DM is sent successfully):

 user argument to new_direct_message deprecated; use screen_name or user_id at /usr/local/share/perl/5.10.1/Net/Twitter/Role/API/RESTv1_1.pm line 385.

This is via the following line of code:
 $nt->new_direct_message( 'target_user', 'This is a test text');

It might be nice if the documentation gave an example of using the screen_name param. I.e.

$nt->new_direct_message( 'This is a test text', { screen_name => 'target_user' } )

Below is the module details i ahve:

 M/MM/MMIMS/Net-Twitter-4.01002.tar.gz
        /usr/local/share/perl/5.10.1/Net/Twitter.pm
        Installed: 4.00006
        CPAN:      4.01002  Not up to date
        Marc Mims (MMIMS)
        mmims@cpan.org

**Comment by semifor** [comment]
This is apparently no longer applicable. I don't find any documentation illustrating the positional parameter style with target ID and text. Please re-open if I'm missing something. And thanks for the issue. My apologies it has taken so long.
