### ISSUE TITLE
Add application-only authentication support

### ISSUE THREAD

**Issue by ribugent** [semifor/Net-Twitter#42]
The current implementation don't have support for this feature now, it will be useful for some kind of applications.

Thanks in advance.

**Comment by semifor** [comment]
Added in 2714dfa. I haven't released, yet. Hoping to get some feedback from Twitter regarding the `invalidate_token` method, which doesn't work as documented.

**Comment by semifor** [comment]
Released: https://metacpan.org/release/MMIMS/Net-Twitter-4.01009
