### ISSUE TITLE
Invalid version format (non-numeric data) at /loader/0x1bed638/App/cpanminus/script.pm line 1134

### ISSUE THREAD

**Issue by michichan** [semifor/Net-Twitter#45]
Yes, I am aware of a previous thread on this.. but upgrading cpanm is not working.  I am getting this message on any of the 4.x versions.  

<pre>
root@rectest:/home/cdbs# cpanm --self-upgrade
App::cpanminus is up to date. (1.7001)
root@rectest:/home/cdbs# cpanm --version
cpanm (App::cpanminus) version 1.5007
root@rectest:/home/cdbs# cpanm Net::Twitter
--> Working on Net::Twitter
Fetching http://search.cpan.org/CPAN/authors/id/M/MM/MMIMS/Net-Twitter-4.01004.tar.gz ... OK
Configuring Net-Twitter-4.01004 ... OK
Invalid version format (non-numeric data) at /loader/0x998638/App/cpanminus/script.pm line 1134.
</pre>

Ubuntu 12.04 64-bit on Digital Ocean

**Comment by jmacdotorg** [comment]
FWIW, seeing the above two comments helped me resolve this issue on my own machine. I suffered from confusion stemming from `cpanm --self-upgrade` somehow targeting a different cpanm instance than my perlbrew-bound one. Once I upgraded *that* one (via `perlbrew install-cpanm`), I could `cpanm Net::Twitter` just fine.
