### ISSUE TITLE
Executing Search not ending

### ISSUE THREAD

**Issue by jrc-imente** [semifor/Net-Twitter#46]
Since 23/04 Twitter have problems with some of our programs that search via Net::Twitter.

The problem seems related with issues in Twitter (API Status page https://dev.twitter.com/status)

After investigating we ends with the call to $netTwitter->search never ends and the process start consuming 90-100% CPU.

We though that the problem is that Net::Twitter is performing the search via LWP, we have some experience with LWP and we know that LWP is not managing good timeouts, with some calls that never ends. Looking the code of the component I does not find any control of wrong behaviour of LWP and I think it could be interesting.

We resolve the problem setting a alarm signal to 5s before the function and everything starts to works good.

**Comment by semifor** [comment]
This has thankfully been resolved with updates to dependencies.
