### ISSUE TITLE
Errors from Devel::StackTrace

### ISSUE THREAD

**Issue by jrc-imente** [semifor/Net-Twitter#58]
A process that use Net::Twitter in some scenarios (we setup and alarm to avoid petition last too much) return this error:

panic: attempt to copy freed scalar 3c10e20 to 5895f88 at /usr/local/share/perl/5.14.2/Devel/StackTrace.pm

Looking for seens something related with implementation in Devel::StackTrace

I'm not sure if some workaround could be done in the Net::Twitter::Error component.

some info related with other compoments like Devel::StackTrace

https://rt.perl.org/Public/Bug/Display.html?id=42166
https://rt.perl.org/Public/Bug/Display.html?id=52610
http://www.perlmonks.org/index.pl?node_id=607210

Using perl 5.14.2

Linux 3.2.0-4-amd64 #1 SMP Debian 3.2.65-1+deb7u2 x86_64 GNU/Linux

**Comment by semifor** [comment]
I'm running Net::Twitter in a very similar environment, an a couple dozen hosts with no issues.

This is perl 5, version 14, subversion 2 (v5.14.2) built for x86_64-linux-gnu-thread-multi
Linux #93-Ubuntu SMP Fri May 2 21:31:50 UTC 2014 x86_64 x86_64 GNU/Linux

You might try running with local::lib ensuring you have a full set of all the perl dependencies complied on the local machine. That might resolve the issue if you have a bad XS module somewhere in your stack.

Or, you could modify a local copy of Net::Twitter::Error removing its stack trace support and dependency on Devel::StackTrace.

Hope that helps.

**Comment by semifor** [comment]
Is this still an issue? I've been unable to duplicate it and have received no other reports.
