### ISSUE TITLE
unretweet method

### ISSUE THREAD

**Issue by dAu6jARL** [semifor/Net-Twitter#82]
unretweet method as following don't exist in Net::Twitter::Role::API::RESTv1_1.
https://developer.twitter.com/en/docs/twitter-api/v1/tweets/post-and-engage/api-reference/post-statuses-unretweet-id

**Comment by semifor** [comment]
Hi @dAu6jARL. Net::Twitter has been deprecated in favor of [Twitter::API](https://metacpan.org/pod/Twitter::API). It has support for `unretweet`. It can also be used to call make API calls Twitter adds that are not explicitly included in [Twitter::API::Trait::ApiMethods](https://metacpan.org/pod/Twitter::API). And, support for Twitter's APIv2 is forthcoming in Twitter::API. You'll find some preliminary, experimental work for it here on Github, [Twitter::API api-v2 branch](https://github.com/semifor/Twitter-API/tree/api-v2)

**Comment by dAu6jARL** [comment]
Thank you for your reply. I'll try Twitter::API.
